import "./globals.css";
import Header from "../components/header/header.jsx";
import Footer from "../components/footer/footer.jsx";

export const metadata = {
  title: "Laalabs Pvt Ltd",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
